# Generated by Django 5.0.3 on 2026-03-05 08:41

import datetime
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeightLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('weight', models.FloatField(help_text='kg')),
                ('date', models.DateField(db_index=True, default=datetime.date.today)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weight_logs', to='organizations.organization')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
