# Generated by Django 5.0.3 on 2026-03-08 13:17

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0002_seed_exercises'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='workoutprogram',
            name='assigned_to',
            field=models.ForeignKey(blank=True, help_text='User this program is assigned to (by trainer)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_programs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='ProgramExercise',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('order', models.PositiveIntegerField(default=0)),
                ('target_sets', models.PositiveIntegerField(default=3)),
                ('target_reps', models.PositiveIntegerField(default=10)),
                ('target_weight', models.FloatField(default=0, help_text='kg')),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='program_exercises', to='workouts.exercise')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='program_exercises', to='workouts.workoutprogram')),
            ],
            options={
                'ordering': ['order'],
                'indexes': [models.Index(fields=['program', 'order'], name='workouts_pr_program_4e9d32_idx')],
                'unique_together': {('program', 'exercise')},
            },
        ),
    ]
