/**
 * Централизованная карта иконок (Lucide React)
 * Единый источник иконок для всего приложения
 */
import {
  // Navigation
  LayoutDashboard,
  Dumbbell,
  UtensilsCrossed,
  TrendingUp,
  Bot,
  User,
  Users,
  Building2,
  // Actions
  Plus,
  Minus,
  Pencil,
  Trash2,
  Search,
  X,
  Check,
  ChevronDown,
  ChevronUp,
  ChevronLeft,
  ChevronRight,
  Settings,
  LogOut,
  Send,
  // Fitness / domain
  Flame,
  Trophy,
  Target,
  Zap,
  Timer,
  Play,
  Pause,
  BarChart3,
  Scale,
  Ruler,
  Heart,
  Activity,
  Apple,
  Coffee,
  Sun,
  Moon,
  Cookie,
  // UI
  AlertTriangle,
  Info,
  Bell,
  Calculator,
  FolderOpen,
  Calendar,
  Sparkles,
  BrainCircuit,
  Shield,
  UserPlus,
  Loader2,
  Hash,
  Weight,
  ArrowUp,
  ArrowDown,
  TrendingDown,
  Mail,
  Lock,
  Flag,
  ClipboardList,
  GripVertical,
} from 'lucide-react'

export const NAV_ICONS = {
  home:          LayoutDashboard,
  workouts:      Dumbbell,
  nutrition:     UtensilsCrossed,
  progress:      TrendingUp,
  ai:            Bot,
  profile:       User,
  members:       Users,
  organizations: Building2,
}

export const ACTION_ICONS = {
  add:         Plus,
  remove:      Minus,
  edit:        Pencil,
  delete:      Trash2,
  search:      Search,
  close:       X,
  check:       Check,
  chevronDown: ChevronDown,
  chevronUp:   ChevronUp,
  chevronLeft: ChevronLeft,
  chevronRight:ChevronRight,
  settings:    Settings,
  logout:      LogOut,
  send:        Send,
  info:        Info,
  bell:        Bell,
  userPlus:    UserPlus,
  shield:      Shield,
  loader:      Loader2,
  warning:     AlertTriangle,
}

export const DOMAIN_ICONS = {
  flame:       Flame,
  trophy:      Trophy,
  target:      Target,
  zap:         Zap,
  timer:       Timer,
  play:        Play,
  pause:       Pause,
  barChart:    BarChart3,
  scale:       Scale,
  ruler:       Ruler,
  heart:       Heart,
  activity:    Activity,
  apple:       Apple,
  coffee:      Coffee,
  sun:         Sun,
  moon:        Moon,
  cookie:      Cookie,
  calculator:  Calculator,
  folder:      FolderOpen,
  calendar:    Calendar,
  sparkles:    Sparkles,
  brain:       BrainCircuit,
  dumbbell:    Dumbbell,
  hash:        Hash,
  weight:      Weight,
  arrowUp:     ArrowUp,
  arrowDown:   ArrowDown,
  trendingUp:  TrendingUp,
  trendingDown:TrendingDown,
}

export const MEAL_ICONS = {
  breakfast: Coffee,
  lunch:     Sun,
  dinner:    Moon,
  snack:     Cookie,
}

// Re-export individual for direct usage
export {
  LayoutDashboard, Dumbbell, UtensilsCrossed, TrendingUp, Bot, User, Users,
  Building2, Plus, Minus, Pencil, Trash2, Search, X, Check, ChevronDown,
  ChevronUp, ChevronLeft, ChevronRight, Settings, LogOut, Send, Flame,
  Trophy, Target, Zap, Timer, Play, Pause, BarChart3, Scale, Ruler, Heart,
  Activity, Apple, Coffee, Sun, Moon, Cookie, AlertTriangle, Info, Bell,
  Calculator, FolderOpen, Calendar, Sparkles, BrainCircuit, Shield, UserPlus,
  Loader2, Hash, Weight, ArrowUp, ArrowDown, TrendingDown,
  Mail, Lock, Flag, ClipboardList, GripVertical,
}
