# Generated by Django 5.0.3 on 2026-03-05 08:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('nutrition', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='foodlog',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='food_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='foodlog',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='nutrition.foodproduct'),
        ),
        migrations.AddIndex(
            model_name='foodlog',
            index=models.Index(fields=['organization', 'user', 'date'], name='nutrition_f_organiz_8578e8_idx'),
        ),
    ]
