# Generated by Django 5.0.3 on 2026-03-06 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0003_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='foodlog',
            options={'ordering': ['-date', '-created_at']},
        ),
        migrations.AddField(
            model_name='foodlog',
            name='calories',
            field=models.FloatField(default=0, help_text='Calculated kcal for this log entry'),
        ),
        migrations.AddField(
            model_name='foodlog',
            name='carbs',
            field=models.FloatField(default=0, help_text='Calculated carbs (g) for this log entry'),
        ),
        migrations.AddField(
            model_name='foodlog',
            name='fat',
            field=models.FloatField(default=0, help_text='Calculated fat (g) for this log entry'),
        ),
        migrations.AddField(
            model_name='foodlog',
            name='protein',
            field=models.FloatField(default=0, help_text='Calculated protein (g) for this log entry'),
        ),
        migrations.AddField(
            model_name='foodproduct',
            name='brand',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='foodproduct',
            name='name',
            field=models.CharField(db_index=True, max_length=200, unique=True),
        ),
    ]
